package com.nullhorizon.pc.ui

object Strings {
    const val app_name = "NULL HORIZON"
    const val boot_status = "Systems offline. Awaiting emergency interface."

    const val profile_setup_subtitle = "Create a local operator profile. No account is required."
    const val profile_display_name_label = "Operator callsign"
    const val profile_no_account_required = "Stored on this device only."
    const val profile_continue = "Enter emergency interface"

    const val nav_ship_map = "SHIP MAP"
    const val nav_missions = "MISSIONS"
    const val nav_skills = "SKILLS"
    const val nav_settings = "SETTINGS"
    const val nav_ship_map_a11y = "Navigate to ship map"
    const val nav_missions_a11y = "Navigate to mission list"
    const val nav_skills_a11y = "Navigate to skill map"
    const val nav_settings_a11y = "Navigate to settings"
    const val nav_keybind_hint = "1-4 SWITCH · ENTER SELECT"

    const val ship_map_title = "SHIP MAP"
    const val ship_map_subtitle = "REGION SCHEMATIC — SYSTEMS UNLOCK WITH CAMPAIGN PROGRESS"
    fun ship_map_selected(arg1: String, arg2: String): String =
        "REGION: ${arg1.uppercase()} — ${arg2.uppercase()}"
    const val ship_map_systems = "SYSTEMS"

    const val missions_title = "Missions"
    const val missions_subtitle = "Vertical-slice missions are listed first. Select one to begin."
    const val missions_loading = "Loading missions\u2026"
    const val mission_status_available = "Available"
    const val mission_status_locked = "Locked"
    const val mission_status_completed = "Completed"
    const val mission_back = "Back to missions"
    const val mission_begin = "Begin repair"
    const val mission_offline_fallback = "Offline fallback"
    const val mission_systems_panel = "Systems panel"
    const val mission_terminal = "Terminal"
    fun mission_terminal_cwd(arg1: String): String = "cwd: $arg1"
    const val mission_terminal_empty = "No commands yet. Try pwd or ls."
    const val mission_terminal_input = "Command"
    const val mission_terminal_run = "Run"
    const val mission_git = "Git"
    fun mission_git_branch(arg1: String): String = "branch: $arg1"
    const val mission_git_log = "Commit graph"
    const val mission_git_conflicts = "Merge conflicts"
    const val mission_git_use_ours = "Use ours"
    const val mission_git_use_theirs = "Use theirs"
    const val mission_git_empty = "No git commands yet. Try git status."
    const val mission_git_input = "Git command"
    const val mission_git_run = "Run"
    const val mission_sql = "SQL console"
    fun mission_sql_database(arg1: String, arg2: String): String = "database: $arg1 ($arg2)"
    const val mission_sql_schema = "Schema"
    const val mission_sql_schema_empty = "No tables in this mission database."
    fun mission_sql_sample(arg1: String): String = "Sample rows: $arg1"
    const val mission_sql_result = "Result"
    const val mission_sql_result_empty = "No query result yet. Try SELECT \u2026"
    fun mission_sql_result_truncated(arg1: Int): String = "Showing 20 of $arg1 rows"
    const val mission_sql_input = "SQL query"
    const val mission_sql_run = "Run query"
    const val mission_editor = "Code editor"
    const val mission_editor_undo = "Undo"
    const val mission_editor_redo = "Redo"
    const val mission_editor_show_diff = "Show diff"
    const val mission_editor_hide_diff = "Hide diff"
    const val mission_editor_symbols = "Symbols"
    const val mission_test_console = "Test console"
    const val mission_test_console_empty = "No test run yet."
    const val mission_run_tests = "Run tests"
    const val mission_service_map = "Service map"
    const val mission_service_map_nodes = "Services"
    const val mission_service_map_edges = "Links"
    const val mission_pipeline = "Data pipeline"
    fun mission_pipeline_run(arg1: String, arg2: String): String = "Run $arg1 \u00b7 outcome $arg2"
    const val mission_pipeline_stages = "Stages"
    const val mission_mlops = "ML infrastructure"
    const val mission_mlops_artifacts = "Lifecycle artifacts"
    const val mission_objectives = "Objectives"
    const val mission_request_hint = "Request hint"
    fun mission_hint_item(arg1: Int, arg2: String): String = "Hint $arg1: $arg2"
    const val mission_reset = "Reset mission"
    const val mission_completed = "Mission complete"
    fun mission_phase(arg1: String): String = "Phase: $arg1"
    const val debrief_title = "Debrief"
    fun debrief_assisted(arg1: Int): String = "Assisted completion (hint level $arg1)"
    fun debrief_unassisted(arg1: Int): String = "Unassisted completion (hint level $arg1)"
    fun debrief_clearance(arg1: Int): String = "Clearance +$arg1"
    fun debrief_rank(arg1: String): String = "Rank: $arg1"
    const val debrief_mastery = "Mastery updates"
    fun debrief_rewards(arg1: String): String = "Unlocked: $arg1"
    const val debrief_review = "Suggested review"

    const val skills_title = "Skill map"
    const val skills_subtitle = "Mastery evidence from repairs. No public scores \u2014 only operational readiness."
    const val skills_loading = "Loading skill map\u2026"
    fun skills_rank_line(arg1: String, arg2: Int): String = "Rank $arg1 \u00b7 clearance $arg2"
    const val skills_review_title = "Suggested review"
    fun skills_node_mastery(arg1: String, arg2: Int, arg3: Int): String =
        "Mastery: $arg1 \u00b7 evidence $arg2 \u00b7 unassisted $arg3"
    fun skills_node_related(arg1: String): String = "Related: $arg1"

    const val settings_title = "Settings"
    fun settings_profile_section(arg1: String): String = "Local operator: $arg1"
    const val settings_no_account =
        "No account required. Opening campaign progress stays on this device unless you opt into cloud sync later."
    const val settings_privacy_section = "Privacy"
    const val settings_privacy_summary =
        "Analytics and crash reporting are off by default. Online code execution transmits source only when you run an online mission. See PRIVACY.md in the project docs."
    const val settings_analytics = "Allow analytics"
    const val settings_crash_reporting = "Allow crash reporting"
    const val settings_data_section = "Your data"
    const val settings_export_data = "Export local data"
    const val settings_export_preview = "Export preview"
    const val settings_delete_data = "Delete local data"
    const val settings_delete_confirm_title = "Delete local data?"
    const val settings_delete_confirm_body =
        "This removes your local operator profile, mission progress, and privacy settings from this device. You will return to profile setup."
    const val settings_delete_confirm_action = "Delete"
    const val settings_delete_cancel = "Cancel"
    const val settings_accessibility_section = "Accessibility"
    const val settings_high_contrast = "High contrast"
    const val settings_reduced_motion = "Reduced motion"
    const val settings_larger_text = "Larger text"
}
